[package]
name = "get_ranking"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "get_ranking"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.2.5", features = ["derive"] }
csv = "1.1.6"
serde = { version = "1.0.137", features = ["derive"] }
